# Generated by Django 3.0.6 on 2020-05-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='displayname',
        ),
    ]
